import os

KAFKA_HOST=os.getenv('KAFKA_HOST')
KAFKA_TOPIC=os.getenv('KAFKA_TOPIC')
KAFKA_KEY=os.getenv('KAFKA_KEY')
PATH_DATA=os.getenv('PATH_DATA')
TWITTER_CONSUMER_KEY=os.getenv('TWITTER_CONSUMER_KEY')
TWITTER_CONSUMER_SECRET=os.getenv('TWITTER_CONSUMER_SECRET')
TWITTER_ACCESS_TOKEN_KEY=os.getenv('TWITTER_ACCESS_TOKEN_KEY')
TWITTER_ACCESS_TOKEN_SECRET=os.getenv('TWITTER_ACCESS_TOKEN_SECRET')
WORDS=os.getenv('WORDS')
SPARK_HOME=os.getenv('SPARK_HOME')