version: "3.7"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    network_mode: host
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    extra_hosts:
      - "moby:127.0.0.1"

  kafka:
    image: confluentinc/cp-kafka:latest
    network_mode: host
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    extra_hosts:
      - "moby:127.0.0.1"

  stream_tweets:
    build: "./"
    entrypoint: /entrypoint.sh
    command: ["python", "stream_tweets.py"]
    network_mode: host
    environment:
      WORDS: 'love'
      PYTHONUNBUFFERED: 1
    env_file: app/.env
    volumes:
      - ./app:/app:rw

  producer:
    build: "./"
    entrypoint: /entrypoint.sh
    environment:
      WORDS: 'love'
      PYTHONUNBUFFERED: 1
    command: ["python", "producer.py"]
    depends_on: 
      - stream_tweets
      - kafka
    network_mode: host
    env_file: app/.env
    volumes:
      - ./app:/app:rw
  
  consumer:
    build: "./"
    entrypoint: /entrypoint.sh
    environment:
      WORDS: 'love'
      PYTHONUNBUFFERED: 1
    command: bash -c "chmod +x -R /spark && python consumer.py"
    depends_on: 
      - producer
    network_mode: host
    env_file: app/.env
    volumes:
      - ./app:/app:rw
      - ../spark:/spark:rw